version: "3"

services:
  mysqldb:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: achat
      MYSQL_ROOT_PASSWORD: achat
  app:
    depends_on:
      - mysqldb
    image: khaoulahadrouchi/achat
    restart: always
    ports:
      - 8089:8089
    environment:
      MYSQL_HOST: mysqlCICD
      MYSQL_USER: root
      MYSQL_PASSWORD: achat
volumes:
  db: